baseURL = "http://first-polly-website-bucket.s3-website-us-east-1.amazonaws.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Route to excellence"
theme = "hugo-theme-learn"
defaultContentLanguageInSubdir = true
uglyurls = true

[params]
    description = "A place of excellence"
    author = "Your name"
    showVisitedLinks = true
    pollyMediaURL = "https://s3.REGION.amazonaws.com/YOUR_POLLY_BUCKET"

[Languages]
[Languages.en]
title = "Route to Excellence"
weight = 1
languageName = "English"

[Languages.fr]
title = "Route d'excellence"
weight = 2
languageName = "Français"
